# Generated by Django 3.1.3 on 2020-11-14 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trinker',
            name='dabei',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trinker',
            name='motto',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
