# Generated by Django 3.1.3 on 2020-11-15 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meile', '0002_auto_20201114_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antwort', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gekuesster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gekuesster', to='meile.trinker')),
                ('kuesser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kuesser', to='meile.trinker')),
            ],
        ),
    ]
