# Generated by Django 3.1.3 on 2020-11-15 13:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meile', '0003_kuss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CountdownTeilnehmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erfolg', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('countdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meile.countdown')),
                ('teilnehmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meile.trinker')),
            ],
        ),
    ]
