# Generated by Django 3.1.3 on 2020-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meile', '0004_countdown_countdownteilnehmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='interval',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
